"""Generate the chronium license / profile-encryption secret and bake it
into the three places that need to hold a copy.

The DRM design (see patches/0020-license-gate + scripts/encrypt-profiles.py)
relies on one 32-byte secret shared between:

  1. chrome.dll                  — bakes via `include/license_secret.h`
                                   (`constexpr uint8_t kLicenseSecret[32]`)
  2. Tauri shell (antidetect.exe) — bakes via
                                   `antidetect/shell/src-tauri/src/license.rs`
                                   (`pub const SECRET_HEX`)
  3. encrypt-profiles.py tool    — reads from `config/.profile_key`
                                   (raw 32 bytes)

All three are .gitignore'd. The secret never lives in the source repo, only
in compiled binaries (chrome.dll, antidetect.exe) and on the developer's
machine.

Run ONCE when starting a project. Re-run only when rotating the secret —
note that a rotation invalidates every previously-shipped binary, so
plan it around a major version bump.

Usage:
    python scripts/gen-license-secret.py
    python scripts/gen-license-secret.py --force    # overwrite existing files

By default refuses to overwrite if any of the three targets already
exists, so you can't accidentally torch a working setup by re-running it.
"""

from __future__ import annotations

import argparse
import secrets
import sys
from pathlib import Path
from textwrap import dedent

ROOT = Path(__file__).resolve().parent.parent

# Where the secret-bearing files land. The Rust shell USED to receive a
# generated license.rs with the literal const inside; that was switched
# to a build.rs lookup (CHRONIUM_LICENSE_KEY env var or the .profile_key
# below) so the rs file can stay in git without leaking the secret. The
# C++ header and the raw key file are still emitted directly — those
# don't have a clean compile-time-env equivalent.
H_FILE       = Path("C:/cr/src/chrome/browser/license/license_secret.h")
KEY_FILE     = ROOT / "config" / ".profile_key"


def hex_bytes_cpp(b: bytes) -> str:
    """Format 32 bytes as a C++ constexpr array initializer."""
    rows = []
    for i in range(0, len(b), 8):
        chunk = b[i:i + 8]
        rows.append("    " + ", ".join(f"0x{x:02x}" for x in chunk) + ",")
    return "\n".join(rows)


def write_header_h(b: bytes) -> None:
    # dedent+f-string mishandles the nested `body` indent, so write it
    # column-anchored at 0 instead.
    H_FILE.parent.mkdir(parents=True, exist_ok=True)
    body = hex_bytes_cpp(b)
    content = (
        "// Copyright 2026 The Chronium Authors. All rights reserved.\n"
        "// Use of this source code is governed by a BSD-style license.\n"
        "//\n"
        "// Auto-generated by chronium-build/scripts/gen-license-secret.py\n"
        "// DO NOT COMMIT. DO NOT EDIT BY HAND.\n"
        "//\n"
        "// Sym-shared secret bound to the same value baked into the\n"
        "// antidetect Tauri shell (license.rs) and the profile-encryption\n"
        "// tool (.profile_key). Patches 0020 (license gate) and 0021\n"
        "// (encrypted profile loader) read it via the kLicenseSecret\n"
        "// constant below.\n"
        "//\n"
        "// Rotating this regenerates all three at once but invalidates\n"
        "// every previously-shipped chronium release.\n"
        "\n"
        "#ifndef CHROME_BROWSER_LICENSE_LICENSE_SECRET_H_\n"
        "#define CHROME_BROWSER_LICENSE_LICENSE_SECRET_H_\n"
        "\n"
        "#include <cstdint>\n"
        "\n"
        "namespace chronium {\n"
        "\n"
        "inline constexpr uint8_t kLicenseSecret[32] = {\n"
        f"{body}\n"
        "};\n"
        "\n"
        "}  // namespace chronium\n"
        "\n"
        "#endif  // CHROME_BROWSER_LICENSE_LICENSE_SECRET_H_\n"
    )
    H_FILE.write_text(content, encoding="utf-8")
    print(f"  [C++]    {H_FILE}")


def write_key_file(b: bytes) -> None:
    KEY_FILE.parent.mkdir(parents=True, exist_ok=True)
    KEY_FILE.write_bytes(b)
    print(f"  [raw]    {KEY_FILE}  ({len(b)} bytes)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--force", action="store_true",
        help="Overwrite existing license_secret.h / license.rs / .profile_key.",
    )
    args = ap.parse_args()

    existing = [p for p in (H_FILE, KEY_FILE) if p.exists()]
    if existing and not args.force:
        print("[!] refusing to overwrite existing secret files:")
        for p in existing:
            print(f"      {p}")
        print("\n    Pass --force to rotate the secret (invalidates every")
        print("    previously-shipped chronium binary).")
        return 1

    secret = secrets.token_bytes(32)
    print(f"[gen-license-secret] generated 32 random bytes\n")

    write_header_h(secret)
    write_key_file(secret)

    print()
    print("[done] secret baked into the two targets above.")
    print()
    print("The antidetect Tauri shell picks the secret up at compile time via")
    print("its build.rs (no license.rs to rewrite — that file stays in git).")
    print()
    print("Next steps:")
    print("  1. autoninja -C C:\\cr\\src\\out\\Release chrome    # rebake chrome.dll")
    print("  2. python scripts\\encrypt-profiles.py                # encrypt profiles")
    print("  3. cargo build (via tauri build) from antidetect/    # rebake antidetect.exe")
    return 0


if __name__ == "__main__":
    sys.exit(main())
